# Generated by Django 5.1.3 on 2024-11-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='shop_image/')),
                ('price', models.CharField(max_length=70)),
            ],
        ),
    ]
